### ISSUE TITLE
Better to move discussions to the main repo?

### ISSUE THREAD

**Issue by trusktr** [tweenjs/discuss#7]
I think it may be better to just use a `discussion` label for topics like these, so it is easier to track in one place.

**Comment by dalisoft** [comment]
I don't think so, would be better separate repo for discussion to keep main repo clean

**Comment by trusktr** [comment]
Check this out: https://github.com/vercel/vercel/discussions

**Comment by trusktr** [comment]
Hehe, oh, I saw you requested it in the github.community for your org already. Adding the discussion tab to tween.js main repo will be nicer than here.
